[workspace]
members = [
    "workspace-tools",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Pawe≈Ç Walus <pawel.walus@protonmail.com>"]
homepage = "https://github.com/lorehaven/build-tools"
repository = "https://github.com/lorehaven/build-tools"
license = "MIT"
readme = "README.md"

[workspace.dependencies.anyhow]
version = "1.0"

[workspace.dependencies.clap]
version = "4.5"
features = ["derive"]

[workspace.dependencies.serde_json]
version = "1.0"

[workspace.dependencies.toml]
version = "0.9"

[workspace.dependencies.which]
version = "8.0"
