[workspace]
members = [
    "anvil",
    "ferrous",
]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Pawe≈Ç Walus <pawel.walus@protonmail.com>"]
homepage = "https://github.com/lorehaven/build-tools"
repository = "https://github.com/lorehaven/build-tools"
license = "MIT"
readme = "README.md"

[workspace.dependencies.anyhow]
version = "1.0"

[workspace.dependencies.clap]
version = "4.5"
features = ["derive"]

[workspace.dependencies.colored]
version = "3"

[workspace.dependencies.once_cell]
version = "1.21"

[workspace.dependencies.reqwest]
version = "0.12"
default-features = false
features = ["json", "stream", "rustls-tls"]

[workspace.dependencies.rustyline]
version = "17.0"

[workspace.dependencies.serde_json]
version = "1.0"

[workspace.dependencies.syntect]
version = "5.3"

[workspace.dependencies.tokio]
version = "1.49"
features = ["full"]

[workspace.dependencies.toml]
version = "0.9"

[workspace.dependencies.which]
version = "8.0"

[workspace.dependencies.walkdir]
version = "2.5"
